apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-rb
  namespace: atlas
subjects:
  - kind: ServiceAccount
    name: gateway-sa
    namespace: atlas
roleRef:
  kind: Role
  name: gateway-role
  apiGroup: ""
