apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portal-depl
  name: portal-depl
  namespace: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: atlas-configmap
        - name: WEB_SOCKET_PORT
          valueFrom:
            configMapKeyRef:
              key: WEB_SOCKET_PORT
              name: atlas-configmap
        - name: AIAGENT_CONTROLLER_WEB_SOCKET_PORT
          valueFrom:
            configMapKeyRef:
              key: AIAGENT_CONTROLLER_WEB_SOCKET_PORT
              name: atlas-configmap
        - name: TIMEZONE
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: atlas-configmap
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          valueFrom:
            configMapKeyRef:
              key: NODE_TLS_REJECT_UNAUTHORIZED
              name: atlas-configmap
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: atlas-configmap
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              key: CORS_ORIGINS
              name: atlas-configmap
        - name: ALLOWED_HOSTNAMES
          valueFrom:
            configMapKeyRef:
              key: ALLOWED_HOSTNAMES
              name: atlas-configmap
        - name: GLOBAL_RATE_LIMIT_WINDOW_MS
          valueFrom:
            configMapKeyRef:
              key: GLOBAL_RATE_LIMIT_WINDOW_MS
              name: atlas-configmap
        - name: GLOBAL_RATE_LIMIT
          valueFrom:
            configMapKeyRef:
              key: GLOBAL_RATE_LIMIT
              name: atlas-configmap
        - name: TRUST_PROXY
          valueFrom:
            configMapKeyRef:
              key: TRUST_PROXY
              name: atlas-configmap
        - name: FLUENT_BIT_TCP_HOST
          valueFrom:
            configMapKeyRef:
              key: FLUENT_BIT_TCP_HOST
              name: atlas-configmap
        - name: FLUENT_BIT_TCP_PORT
          valueFrom:
            configMapKeyRef:
              key: FLUENT_BIT_TCP_PORT
              name: atlas-configmap
        - name: DB_DIALECT
          valueFrom:
            configMapKeyRef:
              key: DB_DIALECT
              name: atlas-configmap
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: atlas-configmap
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: atlas-configmap
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: atlas-configmap
        - name: DB_SSL_REJECTUNAUTHORIZED
          valueFrom:
            configMapKeyRef:
              key: DB_SSL_REJECTUNAUTHORIZED
              name: atlas-configmap
        - name: DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              key: DB_SCHEMA
              name: atlas-configmap
        - name: DB_SSL_DISABLED
          valueFrom:
            configMapKeyRef:
              key: DB_SSL_DISABLED
              name: atlas-configmap
        - name: DB_SYNC_ENABLED
          valueFrom:
            configMapKeyRef:
              key: DB_SYNC_ENABLED
              name: atlas-configmap
        - name: DB_SYNC_WITH_ALTER_ENABLED
          valueFrom:
            configMapKeyRef:
              key: DB_SYNC_WITH_ALTER_ENABLED
              name: atlas-configmap
        - name: DB_SYNC_WITH_FORCE_ENABLED
          valueFrom:
            configMapKeyRef:
              key: DB_SYNC_WITH_FORCE_ENABLED
              name: atlas-configmap
        - name: SEARCH_HOST
          valueFrom:
            configMapKeyRef:
              key: SEARCH_HOST
              name: atlas-configmap
        - name: SEARCH_ENGINE
          valueFrom:
            configMapKeyRef:
              key: SEARCH_ENGINE
              name: atlas-configmap
        - name: SEARCH_REGION
          valueFrom:
            configMapKeyRef:
              key: SEARCH_REGION
              name: atlas-configmap
        - name: SEARCH_SERVICE_TYPE
          valueFrom:
            configMapKeyRef:
              key: SEARCH_SERVICE_TYPE
              name: atlas-configmap
        - name: SEARCH_SSL_REJECTUNAUTHORIZED
          valueFrom:
            configMapKeyRef:
              key: SEARCH_SSL_REJECTUNAUTHORIZED
              name: atlas-configmap
        - name: SEARCH_USE_AWS_SIG_V4_SIGNER
          valueFrom:
            configMapKeyRef:
              key: SEARCH_USE_AWS_SIG_V4_SIGNER
              name: atlas-configmap
        - name: SEARCH_ENABLE_SNIFFING
          valueFrom:
            configMapKeyRef:
              key: SEARCH_ENABLE_SNIFFING
              name: atlas-configmap
        - name: SEARCH_CLOUD_ID
          valueFrom:
            configMapKeyRef:
              key: SEARCH_CLOUD_ID
              name: atlas-configmap
        - name: ATLAS_AUTH_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ATLAS_AUTH_SERVICE_ENDPOINT
              name: atlas-configmap
        - name: ATLAS_ADMIN_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ATLAS_ADMIN_SERVICE_ENDPOINT
              name: atlas-configmap
        - name: ATLAS_PORTAL_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ATLAS_PORTAL_SERVICE_ENDPOINT
              name: atlas-configmap
        - name: ATLAS_NOTIFICATION_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ATLAS_NOTIFICATION_SERVICE_ENDPOINT
              name: atlas-configmap
        - name: ATLAS_ANALYTICS_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ATLAS_ANALYTICS_SERVICE_ENDPOINT
              name: atlas-configmap
        - name: ATLAS_GATEWAY_CONTROLLER_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ATLAS_GATEWAY_CONTROLLER_SERVICE_ENDPOINT
              name: atlas-configmap
        - name: ATLAS_HACKATHON_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ATLAS_HACKATHON_SERVICE_ENDPOINT
              name: atlas-configmap
        - name: ATLAS_VAULT_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ATLAS_VAULT_SERVICE_ENDPOINT
              name: atlas-configmap
        - name: ATLAS_AIAGENT_CONTROLLER_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ATLAS_AIAGENT_CONTROLLER_SERVICE_ENDPOINT
              name: atlas-configmap
        - name: COOKIE_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: COOKIE_DOMAIN
              name: atlas-configmap
        - name: ATLAS_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: ATLAS_CLIENT_ID
              name: atlas-secrets
        - name: ATLAS_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: ATLAS_CLIENT_SECRET
              name: atlas-secrets
        - name: ACCESS_TOKEN_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: ACCESS_TOKEN_JWT_SECRET_KEY
              name: atlas-secrets
        - name: CAPTCHA_TOKEN_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: CAPTCHA_TOKEN_JWT_SECRET_KEY
              name: atlas-secrets
        - name: PRE_LOGIN_TOKEN_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: PRE_LOGIN_TOKEN_JWT_SECRET_KEY
              name: atlas-secrets
        - name: DEVICE_TOTP_SETUP_TOKEN_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: DEVICE_TOTP_SETUP_TOKEN_JWT_SECRET_KEY
              name: atlas-secrets
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: atlas-secrets
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: atlas-secrets
        - name: DB_SSL_KEY
          valueFrom:
            secretKeyRef:
              key: DB_SSL_KEY
              name: atlas-secrets
        - name: DB_SSL_CERT
          valueFrom:
            secretKeyRef:
              key: DB_SSL_CERT
              name: atlas-secrets
        - name: DB_SSL_CA
          valueFrom:
            secretKeyRef:
              key: DB_SSL_CA
              name: atlas-secrets
        - name: SEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SEARCH_PASSWORD
              name: atlas-secrets
        - name: SEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              key: SEARCH_USERNAME
              name: atlas-secrets
        - name: SEARCH_API_KEY
          valueFrom:
            secretKeyRef:
              key: SEARCH_API_KEY
              name: atlas-secrets
        - name: SEARCH_SSL_KEY
          valueFrom:
            secretKeyRef:
              key: SEARCH_SSL_KEY
              name: atlas-secrets
        - name: SEARCH_SSL_CERT
          valueFrom:
            secretKeyRef:
              key: SEARCH_SSL_CERT
              name: atlas-secrets
        - name: SEARCH_SSL_CA
          valueFrom:
            secretKeyRef:
              key: SEARCH_SSL_CA
              name: atlas-secrets
        - name: AES_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: AES_ENCRYPTION_KEY
              name: atlas-secrets
        - name: AES_ENCRYPTION_IV
          valueFrom:
            secretKeyRef:
              key: AES_ENCRYPTION_IV
              name: atlas-secrets
        - name: PORT
          value: '8082'
        - name: SERVICE_NAME
          value: PORTAL
        - name: SERVICE_VERSION
          value: v1000.1.0-beta
        - name: CORE_VERSION
          value: v3000.0.21
        image: 911167904591.dkr.ecr.ap-south-1.amazonaws.com/atlas-api-manager-portal-service:c-v3000.0.21-s-v1000.1.0-beta
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /portal/health-check
            port: 8082
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: portal-app
        ports:
        - containerPort: 8082
          name: portal-port
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /portal/health-check
            port: 8082
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
      restartPolicy: Always
      serviceAccountName: portal-sa
