apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rb
  namespace: atlas
subjects:
  - kind: ServiceAccount
    name: admin-sa
    namespace: atlas
roleRef:
  kind: Role
  name: admin-role
  apiGroup: ""
