apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devportal-depl
  name: devportal-depl
  namespace: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devportal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devportal
    spec:
      containers:
        - env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: atlas-configmap
            - name: ATLAS_AUTH_SERVICE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ATLAS_AUTH_SERVICE_ENDPOINT
                  name: atlas-configmap
            - name: ATLAS_ADMIN_SERVICE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ATLAS_ADMIN_SERVICE_ENDPOINT
                  name: atlas-configmap
            - name: ATLAS_PORTAL_SERVICE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ATLAS_PORTAL_SERVICE_ENDPOINT
                  name: atlas-configmap
            - name: ATLAS_NOTIFICATION_SERVICE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ATLAS_NOTIFICATION_SERVICE_ENDPOINT
                  name: atlas-configmap
            - name: ATLAS_ANALYTICS_SERVICE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ATLAS_ANALYTICS_SERVICE_ENDPOINT
                  name: atlas-configmap
            - name: ATLAS_GATEWAY_CONTROLLER_SERVICE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ATLAS_GATEWAY_CONTROLLER_SERVICE_ENDPOINT
                  name: atlas-configmap
            - name: ATLAS_HACKATHON_SERVICE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ATLAS_HACKATHON_SERVICE_ENDPOINT
                  name: atlas-configmap
            - name: ATLAS_VAULT_SERVICE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ATLAS_VAULT_SERVICE_ENDPOINT
                  name: atlas-configmap
            - name: ATLAS_AIAGENT_CONTROLLER_SERVICE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ATLAS_AIAGENT_CONTROLLER_SERVICE_ENDPOINT
                  name: atlas-configmap
            - name: NEXT_PUBLIC_APP_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_APP_URL
                  name: atlas-configmap
            - name: ALLOWED_REMOTE_PATTERNS
              valueFrom:
                configMapKeyRef:
                  key: ALLOWED_REMOTE_PATTERNS
                  name: atlas-configmap
            - name: ATLAS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: ATLAS_CLIENT_ID
                  name: atlas-secrets
            - name: ATLAS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: ATLAS_CLIENT_SECRET
                  name: atlas-secrets
            - name: ACCESS_TOKEN_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: ACCESS_TOKEN_JWT_SECRET_KEY
                  name: atlas-secrets
            - name: PORT
              value: "8087"
          image: 911167904591.dkr.ecr.ap-south-1.amazonaws.com/atlas-api-manager-developerportal-service:ACCPOCDC-PROD-v515.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 8087
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          name: devportal-app
          ports:
            - containerPort: 8087
              name: devportal-port
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 8087
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
      restartPolicy: Always
      serviceAccountName: devportal-sa
