kind: CronJob
apiVersion: batch/v1
metadata:
  name: api-deprecations-manager-cron-job
  namespace: atlas
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  startingDeadlineSeconds: 30
  suspend: false
  schedule: "30 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -ec
                - "curl --location --request POST 'http://admin-svc.atlas.svc.cluster.local:8081/admin/v1/api-versions/internal/manage-deprecations'
                  --header 'x-atlas-client-id: Atlas-Developer-Portal-Microservice'
                  --header 'x-atlas-client-secret: C?NPwXUW=Gc5pNsC?no9xnAr*cjX}3JN7>~-dc27Bv2sV+cWD3*9DH2'"
              image: curlimages/curl:7.86.0
              imagePullPolicy: IfNotPresent
              name: api-deprecations-manager
          restartPolicy: OnFailure
