apiVersion: v1
kind: Service
metadata:
  name: noti-svc # Service Name
  namespace: atlas # Service Namespace
  annotations: {}
spec:
  selector:
    app: notification # Map the Service with the specified selected Pods
  type: ClusterIP # Internal Service to be used by other PODs / Services only.
  ports:
    - name: noti-svc-port # Name of the PORT
      port: 8083 # Service Port Number
      targetPort: noti-port # Redirect to Application PORT
      protocol: TCP # TCP Protocol
