apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-rb
  namespace: atlas
subjects:
  - kind: ServiceAccount
    name: auth-sa
    namespace: atlas
roleRef:
  kind: Role
  name: auth-role
  apiGroup: ""
