name: Helm Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your current repo
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: nayanmore777/poc-pfl-helm
          ref: main

      # Step 2: Copy Helm chart to Bastion
      - name: Copy Helm chart to Bastion
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 3.110.134.202
          username: ec2-user
          key: ${{ secrets.BASTION_SSH_KEY }}
          source: templates
          target: /home/ec2-user/deploy

      # Step 3: SSH into Bastion & Deploy Helm chart
      - name: Deploy Helm chart on Bastion
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 3.110.134.202
          username: ec2-user
          key: ${{ secrets.BASTION_SSH_KEY }}
          script: |
            set -e
            cd /home/ec2-user/deploy/templates

            # Install Helm if missing
            if ! command -v helm &> /dev/null; then
              curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            fi

            # Update kubeconfig
            aws eks update-kubeconfig --region ap-south-1 --name atlas-dc-eks-cluster

            # Deploy chart
            helm upgrade --install my-release . --namespace atlas --create-namespace
